import { Metadata } from "next";

export const metadata : Metadata = {
  //title por medio de object, mas flexible y "inteligente"  
  title: {
    //abmite tres clavesde forma:
    absolute:"",//para ignorar segmentos principales. ve a dashboard para ver ejemplo
    default: "Learn js - Faebb",//predeterminada util para las rutas hijas que no especifican el titulo
    template: "%s | Faebb",//para agregar prefijos o sufijos en las rutas hijas no en la que se define
  },
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="es">
      <body>
        <header style={{ backgroundColor: "lightblue", padding: "1rem" }}>
          <p>Header</p>
        </header>
        {children}
        <footer
          style={{
            backgroundColor: "ghostwhite",
            padding: "1rem",
          }}
        >
          Footer
        </footer>
      </body>
    </html>
  );
}
